export enum BaseToken {
  APP_CONFIG = 'APP_CONFIG',
  DB_CONTEXT = 'DB_CONTEXT',
  DOMAIN_EVENT_DISPATCHER = 'DOMAIN_EVENT_DISPATCHER',
  INFRASTRUCTURE_EVENT_DISPATCHER = 'INFRASTRUCTURE_EVENT_DISPATCHER',
}
