GOOGLE_OAUTH_CALLBACK_URL=http://localhost:8080/auth/oauth/google-callback
PASSWORD_RESET_REDIRECT_URL=http://localhost:3000/reset
CLIENT_AUTH_REDIRECT_URL=http://localhost:3000/sign-in
PASSWORD_RECOVERY_TIME=900
BILLING_SUCCESS_REDIRECT_URL=http://localhost:3000/billing
TRIAL_PERIOD_DURATION_DAYS=14

SUPABASE_URL=$SUPABASE_URL
SUPABASE_SECRET_KEY=$SUPABASE_SECRET_KEY
GOOGLE_OAUTH_CLIENT_ID=$GOOGLE_OAUTH_CLIENT_ID
GOOGLE_OAUTH_SECRET=$GOOGLE_OAUTH_SECRET
DB_URL=$DB_URL
STRIPE_API_KEY=$STRIPE_API_KEY
STRIPE_WEBHOOK_SIGNING_SECRET=$STRIPE_WEBHOOK_SIGNING_SECRET
