export enum BillingDiToken {
  SUBSCRIPTION_PLANS_PROVIDER_SERVICE = 'SUBSCRIPTION_PLANS_PROVIDER_SERVICE',
  CUSTOMER_PROVIDER_SERVICE = 'CUSTOMER_PROVIDER_SERVICE',
  PAYMENT_CUSTOMER_REPOSITORY = 'PAYMENT_CUSTOMER_REPOSITORY',
  ARRANGE_SUBSCRIPTION_USE_CASE = 'ARRANGE_SUBSCRIPTION_USE_CASE',
  UPGRADE_SUBSCRIPTION_USE_CASE = 'UPGRADE_SUBSCRIPTION_USE_CASE',
  CANCEL_SUBSCRIPTION_USE_CASE = 'CANCEL_SUBSCRIPTION_USE_CASE',
  LIST_SUBSCRIPTION_PLANS_USE_CASE = 'LIST_SUBSCRIPTION_PLANS_USE_CASE',
}
